[package]
name = "rita"
version = "0.1.7"
edition = "2021"
rust-version = "1.75.0"

description = "2D and 3D Randomized Incremental Triangulation Algorithms"
keywords = [
    "computer-graphics",
    "triangulations",
    "delaunay",
    "geometry",
    "math",
]
categories = ["algorithms", "graphics"]

repository = "https://github.com/glennDittmann/rita"
authors = ["Glenn Dittmann <glenn.dittmann@posteo.de>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
geogram_predicates = "0.2.1"
log = "0.4"
nalgebra = "0.33"
rayon = "1.10"
arbitrary = { version = "1.4", optional = true }

[dev-dependencies]
rita_test_utils = { version = "0.1", path = "../rita_test_utils" }
