name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt --check --all
        continue-on-error: true
      - name: Lint
        run: cargo clippy --all
      - name: Test
        run: cargo test
